name: Fetch Stock Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install yfinance

    - name: Run stock fetcher
      run: python fetch/fetch_stockdata.py

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add public/stock_data.json
        git commit -m "Auto-update stock data" || echo "No changes"
        git push
